models:
  qwen3-0.6b:
    name: "Qwen/Qwen3-Embedding-0.6B"
    type: "embeddings"

  gemma-300M:
    name: "google/embeddinggemma-300M"
    type: "embeddings"

#  splade-large-doc:
#    name: "naver/efficient-splade-VI-BT-large-doc"
#    type: "sparse-embeddings"

  splade-large-query:
    name: "naver/efficient-splade-VI-BT-large-query"
    type: "sparse-embeddings"
    
  bge-v2-m3:
    name: "BAAI/bge-reranker-v2-m3"
    type: "rerank"
